#!/bin/sh

# argon
uci batch <<EOF
set argon.@global[0].primary='#bc1142'
set argon.@global[0].dark_primary='#bc1142'
set argon.@global[0].blur='10'
set argon.@global[0].blur_dark='10'
set argon.@global[0].transparency='0.5'
set argon.@global[0].transparency_dark='0.5'
set argon.@global[0].mode='normal'
set argon.@global[0].online_wallpaper='none'
EOF
uci commit argon

# turboacc bbr_cca is on
uci set turboacc.config.bbr_cca='1'
uci commit turboacc

sed -i "/ace/d" /etc/opkg/distfeeds.conf
sed -i "/passwall_packages/d" /etc/opkg/distfeeds.conf
sed -i "/passwall/d" /etc/opkg/distfeeds.conf
sed -i "/passwall2/d" /etc/opkg/distfeeds.conf

uci batch <<EOF
delete firewall.@zone[0].network
add_list firewall.@zone[0].network='lan'
add_list firewall.@zone[0].network='lan6'
EOF
uci commit firewall
/etc/init.d/firewall restart

# dnsmasq
uci batch <<EOF
delete dhcp.@dnsmasq[0].boguspriv
delete dhcp.@dnsmasq[0].filterwin2k
delete dhcp.@dnsmasq[0].authoritative
delete dhcp.@dnsmasq[0].readethers
delete dhcp.@dnsmasq[0].resolvfile
delete dhcp.@dnsmasq[0].nonwildcard
delete dhcp.@dnsmasq[0].filter_a
set dhcp.@dnsmasq[0].nonegcache='1'
set dhcp.@dnsmasq[0].cachesize='10000'
set dhcp.@dnsmasq[0].filter_aaaa='1'
set dhcp.@dnsmasq[0].server='127.0.0.1#5335'
set dhcp.@dnsmasq[0].noresolv='1'
set dhcp.@dnsmasq[0].nohosts='1'
set dhcp.@dnsmasq[0].serversfile='/etc/dnsmasq.d/accelerated-domains.china.conf'
delete dhcp.lan.dhcpv6
delete dhcp.lan.ra
delete dhcp.lan.ra_slaac
delete dhcp.lan.ra_flags
delete dhcp.lan.ndp
set dhcp.lan.ignore='1'
set dhcp.lan.dynamicdhcp='0'
EOF
uci commit dhcp
/etc/init.d/dnsmasq restart

# dnscrypt-proxy2 setting
sed -i 's/START=18/START=99/g' /etc/init.d/dnscrypt-proxy
sed -i 's/127.0.0.53:53/127.0.0.1:5335/g' /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
sed -i 's/ipv6_servers = false/ipv6_servers = true/g' /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
sed -i 's/odoh_servers = false/odoh_servers = true/g' /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
sed -i 's/http3 = false/http3 = true/g' /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
sed -i 's/cache_size = 4096/cache_size = 10240/g' /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
sed -i 's/127.0.0.1:9050/127.0.0.1:1070/g' /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
sed -i 's/127.0.0.1:8888/127.0.0.1:1101/g' /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
#sed -i 's/# proxy/proxy/g' /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
#sed -i 's/# http_proxy/http_proxy/g' /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
#sed -i 's/# blocked_names_file/blocked_names_file/g' /etc/dnscrypt-proxy2/dnscrypt-proxy.toml

# crontabs
echo '* 4 * * 1  wget --no-check-certificate -O /etc/dnsmasq.d/accelerated-domains.china.conf "https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf"' >> /etc/crontabs/root


exit 0
